version: "3"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_PASSWORD:${DB_PASSWORD}
      - POSTGRES_USER:${DB_USER}
      - POSTGRES_DB:${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
  node:
    build: .
    command: "npm run start"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    expose:
      - "8000"
    ports:
      - "8000:8000"